version: 2.1
jobs:
    build:
    docker:
        - image: cimg/base:2021.04
    steps:
        - checkout
        - add_ssh_keys:
            fingerprints:
                - "Maquina123456"
        - run: sudo apt-get update && sudo apt-get upgrade -y
        - run:
            name: "Comandos para deploy en desarrollo"
            command: |
                sudo apt install tidy -y
                git clone --branch circleci-project-setup https://github.com/AndresGuacheta/Parcial3.git
                cd Parcial3/
                tidy index.html
                scp -o StrictHostKeyChecking=no index.html  nfc@192.168.129.4:/var/nfs/index/
 
  
workflows:
    version: 2
    Parcial3ITI:
        jobs:
            - build
       
    
