version: 2.1
jobs:
 build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "	19:7a:9e:17:1b:93:9a:7c:ca:ed:4c:85:a0:1e:41:31"
      - run: sudo apt-get update && sudo apt-get upgrade -y
      - run:
          name: "Comandos Desarrollo"
          command: |
            sudo apt install tidy -y
            git clone --branch circleci-project-setup https://github.com/AndresGuacheta/Parcial3.git
            cd Parcial3/
            tidy index.html
            scp -o StrictHostKeyChecking=no index.html  ubuntu@18.218.223.44:/home/ubuntu/
            ssh  -o StrictHostKeyChecking=no ubuntu@18.218.223.44 "cd /home/ubuntu/; sudo scp -i "key/NFS_keyAWS.pem" -o StrictHostKeyChecking=no index.html  root@10.0.0.145:/var/nfs/general/; exit"
            
 build2:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - add_ssh_keys:
         fingerprints:
           - "f0:e8:42:28:8b:62:f6:24:1e:64:cf:7c:78:9a:a9:5c"
      - run: sudo apt-get update && sudo apt-get upgrade -y
      - run:
          name: "Comandoos Produccion"
          command: |
            sudo apt install tidy -y
            git clone --branch circleci-project-setup https://github.com/AndresGuacheta/Parcial3.git
            cd Parcial3/
            tidy index.html
            scp -o StrictHostKeyChecking=no index.html  Bastion@157.55.181.62
            ssh  -o StrictHostKeyChecking=no Bastion@157.55.181.62 "cd /home/Bastion/; scp -i "key/NFS_key.pem" -o StrictHostKeyChecking=no index.html root@65.52.36.17:/var/nfs/general/; exit"
      
workflows:
   version: 2
   Parcial3Infra:
     jobs:
       - build
       - aprov:
           type: approval
           requires:
             - build
       - build2:
           requires:
             - build
             - aprov
