version: 2.1

 jobs:
   build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "faeb9c8d-98a7-4f14-877b-9e78060dd30c"
      - run: sudo apt-get update && sudo apt-get upgrade -y
      - run:
          name: "Comandos para deploy en desarrollo"
          command: |
            sudo apt install tidy -y
            git clone --branch circleci-project-setup https://github.com/AndresGuacheta/Parcial3.git
            cd Parcial3/
            tidy index.html
            scp -o StrictHostKeyChecking=no index.html  root@ec2-18-116-20-118.us-east-2.compute.amazonaws.com:/var/www/html/
 
  
   
 workflows:
   version: 2
   Parcial3ITI:
     jobs:
       - build
       
       
    
